### ISSUE TITLE
Unbundled front-end

### ISSUE THREAD

**Issue by 0xaaiden** [microsoft/lida#18]
Is it possible to publish the frontend ui currently used for Lida?
Thanks!

**Comment by victordibia** [comment]
Hi @0xaaiden ,

At this time, the core OSS focus is underlying apis with the UI being optional. 
Currently no plans to release the UI at the moment.  

-V.

**Comment by benheymink** [comment]
@victordibia Could you at least make those sample files available? It would be interesting to see how the examples are being converted!

**Comment by benheymink** [comment]
@victordibia Sure, sorry - I should have been more clearer. I wanted to quickly spin up the UI to evaluate the project. Couldn't get it running locally (because of some of the same issues reported in this repo (#25 , #19 etc.).

Ended up installing the package in a replit sandbox online, but first thing I wanted to do is take a look at the sample files the UI presents to try - I wanted to understand the exact markup of those CSV files and JSON files, but couldn't see anywhere in the app to actually view the 'raw' data, if you see what I mean.

**Comment by benheymink** [comment]
<img width="853" alt="Screenshot 2023-08-29 at 17 01 22" src="https://github.com/microsoft/lida/assets/824764/534ad15d-3675-49c0-8341-b8abb316c43a">
Basically the contents of these files @victordibia

**Comment by victordibia** [comment]
Thanks! 

Also the basemap installation issue #19 is addressed by making basemap optional. e.g.`pip install lida[tools]`.  
So going forward, basemap should not be required. 
(basemap is only needed when lida suggests visualization code that includes maps).

```bash 
pip install lida==0.0.8
```
